### ISSUE TITLE
please tell me how to make it working on China Mobile version..

### ISSUE THREAD

**Issue by jy1989** [joestone/Huawei-MATE-CM10.1#1]
I try to flash this rom, everything is good but found that the system cant find my sim card.
my ascend mate model is MT1-T00
so how can I make it working? 

thank you.

**Comment by joestone** [comment]
It is because of RIL framework part. I have MT1-U06 and the RIL was tested on that model. Maybe the modem needs different firmware in the rom which is from MT1-U06 stock rom.

**Comment by jy1989** [comment]
@joestone  
so can I pick the RIL framework part from MT1-T00 firmware?? 
and can u tell me how to do?
